### ISSUE TITLE
Printf with 64bit ints %lld

### ISSUE THREAD

**Issue by alexalkis** [bebbo/amigaos-cross-toolchain#22]
Currently %lld does not print 64 bit ints.
This wasn't working in libnix in gcc-3.4.0, it is working in gcc-3.4.0 with ixemul.

Test code

#include <stdio.h>

int main(int argc, char *argv[])
{
  printf("%lld\n",(long long)1971);
  return 0;
}
m68k-amigaos-gcc -noixemul -O3 -o int64 int64.c

Additionaly, on 6.3.1b the above programs runs in loop, keeps printing "%lld" forever. Ctrl-c works.

**Comment by bebbo** [comment]
please test

**Comment by alexalkis** [comment]
Sort of works.
On sillychess it works on decimals not on hex numbers. %llX prints a 32-bit hex instead of 64-bit.
On the simple test case (in top post here), something weird is happening. It prints 1971 but goes on forever, keeps printing it (like it was in a loop), and needs ctrl-c to break.

**Comment by bebbo** [comment]
I pushed my recent fixes for the compiler. Please rebuild and test again, My local version is printing hex numbers correctly.

`ll = 0x100000001;
ll *= 0x300000;
printf("%llx\n", ll);`

**Comment by alexalkis** [comment]
Cleaned. Removed the whole install directory. And rebuilt.

Still having problems.  Top post's code gives the attached executable with:
~/amiga/gcc6/bin/m68k-amigaos-gcc -noixemul -m68020 -O3 -o int64 int64.c

[int64.zip](https://github.com/bebbo/amigaos-cross-toolchain/files/1016764/int64.zip)

If you run it on amiga, it keeps printing 1971 forever.

Also, on sillychess
Do
git clone https://github.com/alexalkis/sillychess

then
gcc6/bin/m68k-amigaos-gcc -noixemul -m68020 -O3 -fomit-frame-pointer -o silly sillychess/sillychess/src/*.c

do a stack 100000
silly
d
quit

the position key is 64bit.
Amiga gives: Position key: 43C685FE
Should be: Position key: 5FDA8DA743C685FE

everything else prints nicely in sillychess (and didn't prior to your last two pushes)
try
silly
go depth 6
divide 3
quit

**Comment by bebbo** [comment]
Since it's not working on github I uploaded an test archive here: http://franke.ms/download/int64.zip

It contains a source file and the Amiga executable created with `m68k-amigaos-gcc int64.c -o int64 -noixemul -O3 -fomit-frame-pointer -lm` 

So your file should be identical. If not - attach it, mail it, provide it somehow.

**Comment by alexalkis** [comment]
weird
if I use your command line I get no problems in your source code.
BUT
~/amiga/gcc6/bin/m68k-amigaos-gcc -noixemul -m68020 -O3 -o int64 int64.c
this keeps looping.

**Comment by bebbo** [comment]
Ha, found the reason. The difference is:  -fomit-frame-pointer.

If that's missing, my buggy code optimizes the unused frame pointer away - but is also killing the code:

`.LC0:
	.ascii "%lld\12\0"
	.text
	.align	2
	.globl	_main
_main:
	pea 1971.w
	clr.l -(sp)
	pea .LC0
	jsr _printf
	lea (12,sp),sp | this line is also "optimized" away
	clr.l d0
	rts
`

Since .LC0 precedes main, main is invoked again...

**Comment by alexalkis** [comment]
hex doesn't work for me also


int main(int argc, char *argv[])
{
  long long l = 1971;
  long long h = 0xDEADDEADDEADDEAD;
  
  printf("%lld\n", l);
  printf("%llX\n", h);
  return 0;
}

m68k-amigaos-gcc -noixemul -fomit-frame-pointer -O3 -o int64 int64.c
prints 32bit ('DEADDEAD')

**Comment by bebbo** [comment]
`long long h = 0xDEADDEADDEADDEAD;`

h is not initialized with a long long int.

**Comment by alexalkis** [comment]
Ummm, are you sure?

```
#include <stdio.h>
void printBytes(unsigned char *b) {
  for(int i=0; i<8; ++i)
    printf("%2X",*b++);
  printf("\n");
}

int main(int argc, char *argv[])
{
  long long l = 1971;
  unsigned long long h = 0xDEADBEEFDEADBEEF;
  printf("%lld\n", l);
  printf("%llX\n", h);
  printf("%llu\n", h);

  printBytes(&h);
  return 0;
}

```
printBytes prints 'DEADBEEFDEADBEEF'

**Comment by alexalkis** [comment]
This from linux (mind the indianess)
1971
DEADBEEFDEADBEEF
16045690984833335023
EFBEADDEEFBEADDE

**Comment by bebbo** [comment]
link with -lm

**Comment by alexalkis** [comment]
yeap, that was it!

**Comment by bebbo** [comment]
push:
added tracking of the stackpointer. If the stack frame gets removed a correction for sp is added if necessary.

pls test

**Comment by alexalkis** [comment]
The int64.c (code arround 1st post here) works fine with and without -fomit-frame-pointer.
However sillychess stopped working.  Gets a freeze (just the app) when you invoke it with -fomit-frame-pointer, without the fomite-frame-pointer gives Software failure #80000003

**Comment by alexalkis** [comment]
After last push, sillychess runs fine with -fomit-frame-pointer. Crashes with Software failure #80000003 without -fomit-frame-pointer.

**Comment by alexalkis** [comment]
Great. Everything works after last push! :)
